services:

  clarus-drift-detector:
        #image: clarusproject/clarus_edge_drift_detection:0.0.1
        build: ./code/clarus_edge_drift_detector
        env_file: 
          - .env
        container_name: clarus-drift-detector
        hostname: clarus-drift-detector
        ports:
            - 5001:5000
        volumes:
            - ./code/clarus_edge_drift_detector/app/clarus_reports:/app/clarus_reports
            - ./data:/app/data
